### ISSUE TITLE
Issue with elasticsearch container

### ISSUE THREAD

**Issue by fstolzen** [jamct/docker-log#1]
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
	at java.base/java.nio.file.Files.createDirectory(Files.java:693)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:800)
	at java.base/java.nio.file.Files.createDirectories(Files.java:786)
	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:274)
	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:211)
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:271)
	at org.elasticsearch.node.Node.<init>(Node.java:277)
	at org.elasticsearch.node.Node.<init>(Node.java:257)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log

**Comment by jamct** [comment]
Did you enable the persistent volume by uncommenting this lines?

```
  # volumes:
  #   - ./data/elastic:/usr/share/elasticsearch/data
```

You have to create a subfolder "data/elastic" in your project folder first and give write access to this folder.
Or you use named volumes (docker will create a subfolder in "/var/lib/docker/") as described here:
https://docs.docker.com/compose/compose-file/#volume-configuration-reference

**Comment by fstolzen** [comment]
Creating the / data / elastic directory before running docker-compose up was the problem. 

Thanks for the feedback

**Comment by jamct** [comment]
I just added an empty data folder and a hint in Readme.md.
